### ISSUE TITLE
As a user, i should be able to add headers to a Json Web Source

### ISSUE THREAD

**Issue by lostrouter** [rdavisau/jsondatacontext-linqpad#2]
Need the ability to add headers for a web request.

**Comment by rdavisau** [comment]
Hello, yep that's definitely [on the list](https://github.com/rdavisau/jsondatacontext-linqpad/blob/6d2ebb1adcd860ec3ea4318228939419a82388c8/README.md#planned-features). I'll prioritise and get you something to play with in the next day or so.

**Comment by rdavisau** [comment]
I've added this to [v0.0.4](https://github.com/rdavisau/jsondatacontext-linqpad/releases/tag/v0.0.4). The UI is a little naff, my XAML clearly needs work! I'll clean it up in a later release.

You can also intercept and modify a web request before it is sent at runtime using the methods mentioned on the release page, which should give you some more flexibilty too. Let me know how it works out for you.
